default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 50000
  sslmode: require


# development: 
#   <<: *default
#   database: carboncube_ke_db
#   username: carboncube_ke_db_owner
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   host: localhost


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] += "?sslmode=require" %>
  database: carboncube_ke_db
  username: carboncube_ke_db_owner
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 10        # Adjust connection pool size
  reaping_frequency: 10 # Auto-closes stale connections
